baseURL = 'https://rigomoran.com/'
languageCode = 'en-us'
title = 'Rigo Moran'
enableGitInfo = true
enableRobotsTXT = true

[sitemap]
  changeFreq = 'weekly'
  priority = 0.5

[taxonomies]

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = false
    guessSyntax = true
    tabWidth = 4

[[menus.main]]
name = 'About'
pageRef = '/'
weight = 5

[[menus.main]]
name = 'Writing'
pageRef = '/ideas/'
weight = 10

[[menus.main]]
name = 'Notes'
pageRef = '/til/'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects/'
weight = 30

[frontmatter]
lastmod = ['lastmod', ':git', 'date', 'publishDate']

[params]
logo = 'logo'
description = "Rigo Moran's blog on software engineering, tools, and ideas"
author = "Rigo Moran"

[[params.socials]]
name = 'twitter'
url = 'https://twitter.com/rigomoran_'

[[params.socials]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/rodrigomoran'

[[params.socials]]
name = 'github'
url = 'https://github.com/phantompunk'

[[params.socials]]
name = 'stack-overflow'
url = 'https://stackoverflow.com/users/5776586/rodrigo-moran'

[[params.socials]]
name = 'hashnode'
url = 'https://hashnode.com/@rigomoran'
